# Generated by Django 4.0.3 on 2022-06-12 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('items', models.CharField(max_length=1500)),
                ('address', models.TextField()),
                ('quantity', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('phone_num', models.CharField(max_length=10)),
                ('delivery', models.BooleanField(default=False)),
            ],
        ),
    ]
